import { useState } from "react";
import reactLogo from "./assets/react.svg";
import "./App.css";
import { Routes, Route, useNavigate } from "react-router-dom";
import { Student } from "./Student";
import { Teacher } from "./Teacher";
import { EditStudent } from "./EditStudent";
import { EditTeacher } from "./EditTeacher";
import { AddStudent } from "./AddStudent";
import { AddTeacher } from "./AddTeacher";

function App() {
  const [student, setStudent] = useState([
    {
      id: "1",
      name: "Isaac Bowen",
      gender: "Female",
      Std: 9,
      birthdate: "5-9-1990",
      address: "762 Migof Road",
      street: "Zatena Way",
      city: "Ucudawas",
      state: "TX",
      country: "FJ",
      zip: 26901,
      email: "uzuocagu@wor.cf",
      phone: "(641) 984-3113",
    },
    {
      id: "2",
      name: "Steven Thomas",
      gender: "Male",
      Std: 3,
      birthdate: "5-27-1959",
      address: "154 Buha Extension",
      street: "Gunul Glen",
      city: "Ejahisira",
      state: "MD",
      country: "MQ",
      zip: 58254,
      email: "za@wu.co.uk",
      phone: "(933) 606-2393",
    },
    {
      id: "3",
      name: "Tony Floyd",
      gender: "Female",
      Std: 9,
      birthdate: "10-5-1988",
      address: "1755 Vegec Center",
      street: "Buhled Grove",
      city: "Pibdeed",
      state: "NV",
      country: "ET",
      zip: 76260,
      email: "ijluge@wol.tf",
      phone: "(500) 959-3852",
    },
    {
      id: "4",
      name: "Maurice Casey",
      gender: "Female",
      Std: 5,
      birthdate: "7-12-1998",
      address: "1029 Cuzgim Junction",
      street: "Uwopo Parkway",
      city: "Pogkoeco",
      state: "NC",
      country: "BQ",
      zip: 63342,
      email: "povgeluk@lu.ar",
      phone: "(904) 218-3935",
    },
    {
      id: "5",
      name: "ekta bhosale",
      gender: "Female",
      Std: 2,
      birthdate: "5-19-1964",
      address: "701 Dowcu View",
      street: "Ipec Parkway",
      city: "Ciwmofus",
      state: "VA",
      country: "EE",
      zip: 96143,
      email: "okde@tutifo.nc",
      phone: "(231) 468-1336",
    },
    {
      id: "6",
      name: "Dollie Lowe",
      gender: "Female",
      Std: 7,
      birthdate: "9-29-1996",
      address: "814 Wicej Plaza",
      street: "Zukip Junction",
      city: "Kimnute",
      state: "KY",
      country: "CY",
      zip: 10029,
      email: "maikude@usujorak.is",
      phone: "(810) 508-2254",
    },
    {
      id: "7",
      name: "Stella Rivera",
      gender: "Male",
      Std: 3,
      birthdate: "9-16-1982",
      address: "939 Lihpac Manor",
      street: "Vopem View",
      city: "Cisnutij",
      state: "WV",
      country: "LV",
      zip: 43646,
      email: "ni@opefuti.dj",
      phone: "(365) 726-6148",
    },
    {
      id: "8",
      name: "Genevieve Craig",
      gender: "Male",
      Std: 9,
      birthdate: "7-22-1994",
      address: "1266 Zawna Junction",
      street: "Jibba Key",
      city: "Padkehrog",
      state: "SC",
      country: "CF",
      zip: 17466,
      email: "wa@wi.jm",
      phone: "(422) 869-8125",
    },
    {
      id: "9",
      name: "Mildred Peterson",
      gender: "Female",
      Std: 6,
      birthdate: "7-12-1998",
      address: "1060 Sail Trail",
      street: "Canno Terrace",
      city: "Jovkotof",
      state: "IN",
      country: "LA",
      zip: 85616,
      email: "uwice@radisof.fr",
      phone: "(455) 467-9912",
    },
    {
      id: "10",
      name: "Maria Yates",
      gender: "Female",
      Std: 2,
      birthdate: "8-20-1999",
      address: "442 Sohaga Square",
      street: "Betluj Turnpike",
      city: "Filbeig",
      state: "AK",
      country: "KW",
      zip: 76622,
      email: "gewac@nizpol.st",
      phone: "(953) 832-1724",
    },
    {
      id: "11",
      name: "Lula Miles",
      gender: "Female",
      Std: 5,
      birthdate: "2-24-2002",
      address: "267 Pahpac River",
      street: "Puhwir Avenue",
      city: "Howotpu",
      state: "OH",
      country: "OM",
      zip: 38570,
      email: "bujapve@neucaro.me",
      phone: "(668) 786-5597",
    },
    {
      id: "12",
      name: "Harry Zimmerman",
      gender: "Male",
      Std: 5,
      birthdate: "5-25-1989",
      address: "152 Utbi Manor",
      street: "Enuhed Manor",
      city: "Sowofod",
      state: "MT",
      country: "SM",
      zip: 23441,
      email: "vu@coliz.vu",
      phone: "(539) 807-1032",
    },
    {
      id: "13",
      name: "Sally Hoffman",
      gender: "Male",
      Std: 9,
      birthdate: "12-7-1970",
      address: "885 Muwvon Mill",
      street: "Remi Pass",
      city: "Jambedfa",
      state: "ME",
      country: "BE",
      zip: 75068,
      email: "ko@nicto.pt",
      phone: "(780) 416-6302",
    },
    {
      id: "14",
      name: "Louisa Warner",
      gender: "Male",
      Std: 1,
      birthdate: "3-8-1979",
      address: "1074 Zoptod Manor",
      street: "Sothag Way",
      city: "Zafrokrop",
      state: "HI",
      country: "NO",
      zip: 92381,
      email: "nu@wederana.my",
      phone: "(212) 269-2264",
    },
    {
      id: "15",
      name: "Andrew Willis",
      gender: "Female",
      Std: 4,
      birthdate: "7-21-1958",
      address: "1058 Himi Grove",
      street: "Girtow River",
      city: "Ladhuplab",
      state: "MI",
      country: "TV",
      zip: 26722,
      email: "bema@luvza.ac",
      phone: "(881) 864-1864",
    },
    {
      id: "16",
      name: "Jessie McKenzie",
      gender: "Female",
      Std: 8,
      birthdate: "4-28-1973",
      address: "726 Cuwpa Manor",
      street: "Befa Mill",
      city: "Juridsar",
      state: "TN",
      country: "TF",
      zip: 8241,
      email: "lofoza@not.bf",
      phone: "(460) 347-6268",
    },
    {
      id: "17",
      name: "Luke Rhodes",
      gender: "Female",
      Std: 1,
      birthdate: "4-30-1995",
      address: "467 Webuk Street",
      street: "Jefa Path",
      city: "Jeatti",
      state: "MN",
      country: "BH",
      zip: 48446,
      email: "lan@nanep.my",
      phone: "(524) 676-3050",
    },
    {
      id: "18",
      name: "Lillian Hudson",
      gender: "Male",
      Std: 8,
      birthdate: "3-28-1984",
      address: "1532 Jiwtu Pike",
      street: "Beta Path",
      city: "Bohupewa",
      state: "VT",
      country: "MG",
      zip: 88964,
      email: "hadib@papasi.gd",
      phone: "(448) 769-8821",
    },
    {
      id: "19",
      name: "Violet Page",
      gender: "Female",
      Std: 4,
      birthdate: "3-17-1973",
      address: "234 Gume Avenue",
      street: "Vildu Highway",
      city: "Zohevlip",
      state: "NH",
      country: "GG",
      zip: 44530,
      email: "betub@nidbakeg.ci",
      phone: "(437) 354-4112",
    },
  ]);
  const [teacher, setTeacher] = useState([
    {
      id: "1",
      name: "Kenneth Cruz",
      gender: "Male",
      address: "1584 Ruvi Grove",
      street: "Evjet Circle",
      city: "Likpolmu",
      state: "HI",
      country: "CY",
      zip: 51082,
      email: "to@kucu.bg",
      phone: "(629) 884-1262",
    },
    {
      id: "2",
      name: "Rhoda Flowers",
      gender: "Male",
      address: "1368 Kubuz Lane",
      street: "Atcag Heights",
      city: "Uclute",
      state: "VT",
      country: "CR",
      zip: 66212,
      email: "tum@katkahto.tf",
      phone: "(639) 464-7015",
    },
    {
      id: "3",
      name: "Isaiah Owen",
      gender: "Male",
      address: "1848 Budo Extension",
      street: "Hugi Terrace",
      city: "Sigpaiti",
      state: "UT",
      country: "MN",
      zip: 64248,
      email: "uppa@hijovige.al",
      phone: "(505) 714-4507",
    },
    {
      id: "4",
      name: "Willie Gray",
      gender: "Male",
      address: "955 Kiljib Road",
      street: "Guice Lane",
      city: "Saropsa",
      state: "DC",
      country: "CL",
      zip: 64870,
      email: "gugig@mi.kn",
      phone: "(620) 807-6265",
    },
    {
      id: "5",
      name: "Georgie Hubbard",
      gender: "Male",
      address: "421 Jegu Point",
      street: "Gulo Way",
      city: "Sapesga",
      state: "NY",
      country: "UM",
      zip: 36564,
      email: "tuczu@cirjoke.cu",
      phone: "(582) 616-5520",
    },
    {
      id: "6",
      name: "Jeremy Tyler",
      gender: "Male",
      address: "1599 Jewec Terrace",
      street: "Ihile Parkway",
      city: "Regduhah",
      state: "FL",
      country: "MX",
      zip: 8144,
      email: "saj@vuep.tg",
      phone: "(416) 320-4722",
    },
    {
      id: "7",
      name: "Ellen Barber",
      gender: "Male",
      address: "660 Hinjiz Court",
      street: "Lowa Heights",
      city: "Tetrufba",
      state: "WI",
      country: "DE",
      zip: 36818,
      email: "coari@noac.net",
      phone: "(450) 225-2676",
    },
    {
      id: "8",
      name: "Leroy Perkins",
      gender: "Female",
      address: "541 Torib Terrace",
      street: "Fomil Lane",
      city: "Wukesowa",
      state: "NY",
      country: "LS",
      zip: 25886,
      email: "onhe@minuhuwa.es",
      phone: "(836) 792-5946",
    },
    {
      id: "9",
      name: "Kyle Mason",
      gender: "Female",
      address: "1384 Fueh Drive",
      street: "Tofi Key",
      city: "Omhuccu",
      state: "WY",
      country: "TF",
      zip: 77208,
      email: "etdowami@coh.pk",
      phone: "(254) 973-8332",
    },
    {
      id: "10",
      name: "Millie Griffin",
      gender: "Female",
      address: "102 Jeon Point",
      street: "Razic Ridge",
      city: "Awufbi",
      state: "SC",
      country: "ML",
      zip: 61205,
      email: "kizonbi@ej.tn",
      phone: "(269) 921-5918",
    },
    {
      id: "11",
      name: "Cory Singleton",
      gender: "Male",
      address: "1417 Datjeg Glen",
      street: "Heibo Highway",
      city: "Bihdedmow",
      state: "IN",
      country: "PF",
      zip: 22665,
      email: "otisu@be.rs",
      phone: "(648) 929-1186",
    },
    {
      id: "12",
      name: "Alma Gregory",
      gender: "Female",
      address: "1660 Girru Way",
      street: "Cieg Grove",
      city: "Socaku",
      state: "TN",
      country: "DJ",
      zip: 86669,
      email: "gu@sifuvloc.pg",
      phone: "(782) 854-3188",
    },
    {
      id: "13",
      name: "Gary Wade",
      gender: "Female",
      address: "514 Sopfaz Trail",
      street: "Gaiga Parkway",
      city: "Kommelbe",
      state: "OR",
      country: "BW",
      zip: 21142,
      email: "zurtoz@ef.lb",
      phone: "(210) 551-4190",
    },
    {
      id: "14",
      name: "Howard King",
      gender: "Male",
      address: "993 Bume Road",
      street: "Dove River",
      city: "Cumogeb",
      state: "KS",
      country: "KP",
      zip: 2146,
      email: "zo@za.na",
      phone: "(417) 397-2259",
    },
    {
      id: "15",
      name: "Rosie Phelps",
      gender: "Female",
      address: "800 Sopi Boulevard",
      street: "Gaha Extension",
      city: "Coneab",
      state: "TX",
      country: "SY",
      zip: 22009,
      email: "guh@lem.ee",
      phone: "(429) 460-2538",
    },
    {
      id: "16",
      name: "Sadie McGee",
      gender: "Female",
      address: "1422 Nidel Pike",
      street: "Mabum Junction",
      city: "Hacooz",
      state: "ID",
      country: "EC",
      zip: 11854,
      email: "ew@coadnek.kn",
      phone: "(380) 774-4826",
    },
    {
      id: "17",
      name: "Sadie Robbins",
      gender: "Male",
      address: "1855 Ehewa River",
      street: "Febvu Ridge",
      city: "Mazifaw",
      state: "KY",
      country: "CW",
      zip: 51534,
      email: "isoagi@hemetak.gu",
      phone: "(939) 907-3122",
    },
    {
      id: "18",
      name: "Lucas Reeves",
      gender: "Male",
      address: "1595 Hoku Extension",
      street: "Vahcav Square",
      city: "Uvwuhek",
      state: "TX",
      country: "MX",
      zip: 84461,
      email: "suzufvul@pu.za",
      phone: "(321) 743-5601",
    },
    {
      id: "19",
      name: "Ellen Phelps",
      gender: "Female",
      address: "1593 Dowolu Way",
      street: "Orihar Mill",
      city: "Erawanumo",
      state: "VA",
      country: "BL",
      zip: 77483,
      email: "hogtewub@pun.km",
      phone: "(510) 752-6642",
    },
    {
      id: "20",
      name: "Josephine Bryan",
      gender: "Female",
      address: "805 Feige Junction",
      street: "Zictet Trail",
      city: "Tubalta",
      state: "UT",
      country: "BW",
      zip: 39086,
      email: "ju@anemavag.ph",
      phone: "(846) 829-6297",
    },
    {
      id: "21",
      name: "Jerry Marshall",
      gender: "Male",
      address: "1849 Bepbi River",
      street: "Modgol Place",
      city: "Isilomeg",
      state: "NJ",
      country: "BE",
      zip: 18212,
      email: "kob@to.gn",
      phone: "(650) 913-7611",
    },
    {
      id: "22",
      name: "Lee Chambers",
      gender: "Female",
      address: "1488 Bofu Parkway",
      street: "Teglop Manor",
      city: "Kovzobop",
      state: "TX",
      country: "VC",
      zip: 86011,
      email: "poeci@gabre.sx",
      phone: "(732) 520-7641",
    },
    {
      id: "23",
      name: "Mable Daniel",
      gender: "Male",
      address: "79 Zekfe Loop",
      street: "Kikiw Trail",
      city: "Joeloli",
      state: "UT",
      country: "GH",
      zip: 38560,
      email: "woduike@vuk.la",
      phone: "(741) 935-2938",
    },
    {
      id: "24",
      name: "Owen Frazier",
      gender: "Male",
      address: "1326 Vuiw Lane",
      street: "Cavfej Mill",
      city: "Recbogoz",
      state: "CA",
      country: "TH",
      zip: 78579,
      email: "puk@tedo.ge",
      phone: "(259) 946-2412",
    },
  ]);

  const [count, setCount] = useState(0);

  return (
    <div className="App">
      
      <Routes>
        <Route path="/" element={<Home />} />
        <Route
          path="/student-list"
          element={<Student student={student} setStudent={setStudent} />}
        />
        <Route
          path="/student-list/add-student"
          element={<AddStudent student={student} setStudent={setStudent} />}
        />
        <Route
          path="/student-list/edit/:id"
          element={<EditStudent student={student} setStudent={setStudent} />}
        />
        <Route
          path="/teacher-list"
          element={<Teacher teacher={teacher} setTeacher={setTeacher} />}
        />
        <Route
          path="/teacher-list/add-teacher"
          element={<AddTeacher teacher={teacher} setTeacher={setTeacher} />}
        />
        <Route
          path="/teacher-list/edit/:id"
          element={<EditTeacher teacher={teacher} setTeacher={setTeacher} />}
        />

        <Route path="*" element={<Pagenotfound />} />
      </Routes>
    </div>
  );
}


function Home() {
  const navigate = useNavigate();
  return (
    <div className="home">
      <h1>Sign in As</h1>
      <button onClick={() => navigate("/teacher-list")}>Teacher</button>
      <button onClick={() => navigate("/student-list")}>Student</button>
      <button onClick={() => navigate("/student-list")}>Add Teacher</button>
      <button onClick={() => navigate("/student-list/add-student")}>Add Student</button>
    </div>
  );
}

function Pagenotfound() {
  return (
    <div>
      <h1>Page Not Found</h1>
    </div>
  );
}

export default App;
